account/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name="account/logout.html"), name="logout"),
    path("register/", views.SignUp, name="signup"),
    path("", views.home, name="home"),
    path("aboutus/", views.aboutus, name="about-us"),
    path("contact/", views.contact, name="contact"),
    path("myacc/", views.myacc, name="myacc"),
    path("list/",views.list, name="list"),
    path("blogs/", views.blogs, name="blogs"),
    path("womenhealth/", views.womenhealth, name="womenhealth"),
]

appointment/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "appointment"

urlpatterns = [
    path("appointments/p/", views.AppointmentsForAPatientView.as_view(), name="patient-appointments"),
    path("appointments/d/", views.AppointmentsForADoctorView.as_view(), name="doctor-appointments"),
    path("medHistory/", views.MedicalHistoryView.as_view(), name="med-history"),
    path("prescriptions/", views.PrescriptionListView.as_view(), name="doc-prescriptions"),
    path("prescription/create", views.PrescriptionCreateView, name="doc-prescriptions-create"),
    path("appointment/create", views.AppointmentCreateView, name="appointment-create"),
    path("rdashboard/", views.rdashboard, name="r_dashboard"),
    path("hrdashboard/", views.hrdashboard, name="hr_dashboard"),
    path("hraccounting/", views.hraccounting, name="hr_accounting"),
    path("payments/", views.pateintpayments, name="pat_payments"),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('account.urls', namespace="account")),
    path("", include('user_profile.urls', namespace="user_profile")),
    path("", include('appointment.urls', namespace="appointment")),
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'css/ind.css' %}">
 <script src="{% static 'js/dropdown.js' %}"></script>


{% block link %}


{% endblock %}


 <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">

    <title>

        {% block title %}

        {% endblock  %}

    </title>
</head>

{% block header %}

{% endblock  %}

<header class="text-white" id="header">
    <nav class="navbar navbar-expand-lg navbar-dark d-flex">
        <div class="navbar-nav nav-item flex-grow-1">
            <a class="navbar-brand" href="">
                <img class="logo" src="{% static 'pics/medlogo.png' %}" alt="">    </a>
            <div class="h1 mt-2 medisafe">
                MEDISAFE </div>

        </div>

        <div class="d-flex justify-content-between h5" id="headliner">
            <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'account:home' %}">Home</a>
            
            <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'account:blogs' %}">Blogs</a>
            <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'account:womenhealth' %}">FAQs</a>


            {% if user.is_active %}

                {% if user.is_patient %}
                    <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'appointment:patient-appointments' %}">My Appointments</a>
                {% elif user.is_doctor %}
                    <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'appointment:doctor-appointments' %}">My Appointments</a>
                 {% endif %}
                
            <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'account:logout' %}">Logout</a>
            <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'account:myacc' %}">{{ user.username }}</a>
            {% else %}
            <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'account:login' %}">Login</a>
            <a class="nav-item nav-link m-2 btn btn-outline-light" href="{% url 'account:signup' %}">Register</a>
            {% endif %}
                <!--button class="nav-item m-2 btn btn-outline-light dropdown-toggle" onclick="myFunction()"   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Register<i class="fa fa-caret-down"></i></button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="myDropdown">
                    <a class="nav-link" href="https://www.mycareindia.co.in/register-with-us/patient/" >Patient</a>
                    <a class="nav-link" href="https://www.mycareindia.co.in/register-with-us/doctors/" >Doctors</a>
                    <a class="nav-link" href="https://www.mycareindia.co.in/register-with-us/hospital/" >Hospital</a>
                    <a class="nav-link" href="https://www.mycareindia.co.in/register-with-us/pharmacy/" >Pharmacy</a>
                    <a class="nav-link" href="https://www.mycareindia.co.in/register-with-us/pathology-laboratory/" >Pathology Laboratory</a>
                </div-->

        </div>
      </nav>
</header>

<body>


{% block content %}

{% endblock  %}



</body>
<footer id="footer">
    
</footer>
</html>

<!--    Dishant Tayade  S20190010175    -->

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h3>The one of the finest in its category </h3>
   

{% endblock %}